# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~
    
    # La liste des filtres
    filter_sets:
        cache: ~
        # Nom du Filtre (small)
        small_sets:
            format: webp
            # réglez la qualité de l'image sur 60%
            quality: 100

            # liste des transformations à appliquer sur les "filtres"
            filters:
                thumbnail: { size: [200, 150], mode: outbond }
                # Taille de l'image de sortie

        medium:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [400, 400], mode: outbond }

